<form id="co-deliverytime-form" action="">
<li id="timeslot-form">
        <fieldset>
          <ul>
            <li class="wide">
              <div class="delivery_modes timeSlotTable">
                <table class="slots_table" width="100%" border="1" bordercolor="#EBEBE9" style="border-collapse:collapse" cellspacing="0" cellpadding="6">
                  <tr align="center" class="header">
                    <td  height="34" style="vertical-align:middle" class="col1" >Day/Date</td>
                    <td colspan="6" class="tslot_header"><table border="0" width="100%">
                        <tr>
                          <td width="346" height="30" style="text-align:center"> Time Slots </td>
                          <td width="131" style="text-align:right">
                          <a href="javascript:void(0)" id="nextweek" class="delprod"> <span style="font-weight:bold">Next Week</span></a>
                          </td>
                        </tr>
                      </table></td>
                  </tr>
                  <?php 
			  		// set current date
					$date = date('d-m-Y');
					// parse about any English textual datetime description into a Unix timestamp
					$ts1 = strtotime($date);
					// find the year (ISO-8601 year number) and the current week
					$year = date('o', $ts1);
					$week = date('W', $ts1);
					// print week for the current date
					for($i = 1; $i <= 7; $i++) {
					// timestamp from ISO week date format
					$ts = strtotime($year.'W'.$week.$i);	
			      ?>
                  <tr class="<?php echo $i%2==0?'evenRow':'oddRow' ?>">
                    <td class="col1"><?php echo date("d-m-Y D", $ts) ?></td>
            <?php 
			$data_array = Mage::getModel('deliverytime/deliverytime')->getCollection()->addFieldToSelect('*')->addFieldToFilter('status',1); 
			if(count($data_array)>0):
                        foreach($data_array as $key=>$value):
			?>
                    <td style="color:#999999" <?php echo $ts1>$ts?'class="nohover"':''; ?> <?php 
					echo (date("D", $ts)=='Mon' && $value->getmon()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Tue' && $value->gettue()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Wed' && $value->getwed()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Thu' && $value->getthu()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Fri' && $value->getfri()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Sat' && $value->getsat()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Sun' && $value->getsun()==0)?'class="nohover"':'';					
					?>><label class="label">
                        <input id="exp" type="radio" class="btnradio" name="timeslot" value="<?php echo $value->getdeliverytime_start().' - '.$value->getdeliverytime_end().' '.date("d-m-Y D", $ts);?>" <?php 
							echo (date("D", $ts)=='Mon' && $value->getmon()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Tue' && $value->gettue()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Wed' && $value->getwed()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Thu' && $value->getthu()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Fri' && $value->getfri()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Sat' && $value->getsat()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Sun' && $value->getsun()==0)?'disabled="disabled"':'';					
					    ?> <?php echo $ts1>$ts?'disabled="disabled"':''; ?> />
                        <?php echo $value->getdeliverytime_start().' - '.$value->getdeliverytime_end();?></label></td>
                        
             <?php  endforeach; else:  ?>
                    <td> <h3 style="text-align:center;">No Time Slot Available </h3> </td>       
            <?php endif; ?>
                    
                  </tr>
                  <?php } ?>
                  
                  <!-- NEW DELIVERY MODE -->
                </table>
              </div>
              <div class="delivery_modes_nextweek timeSlotTable" >
                <table class="slots_table" width="100%" border="1" bordercolor="#EBEBE9" style="border-collapse:collapse" cellspacing="0" cellpadding="6">
                  <tr align="center" class="header">
                    <td  height="34" style="vertical-align:middle" class="col1" >Day/Date</td>
                    <td colspan="7" class="tslot_header"><table border="0" width="100%">
                        <tr>
                          <td width="346" height="30" style="text-align:center"> Time Slots </td>
                          <td width="131" style="text-align:right">
                          <a href="javascript:void(0)" id="prevweek" class="delprod"><span style="font-weight:bold">Previous Week</span></a>
                          </td>
                        </tr>
                      </table></td>
                  </tr>
                  <?php 
			  		// set current date
					$date = strtotime(date('d-m-Y'));
					// parse about any English textual datetime description into a Unix timestamp
					$ts = strtotime("+7 day", $date);					
					// find the year (ISO-8601 year number) and the current week
					$year = date('o', $ts);
					$week = date('W', $ts);
					// print week for the current date
					for($i = 1; $i <= 7; $i++) {
					// timestamp from ISO week date format
					$ts = strtotime($year.'W'.$week.$i);	
			      ?>
                  <tr class="<?php echo $i%2==0?'evenRow':'oddRow' ?>">
                    <td class="col1"><?php echo date("d-m-Y D", $ts) ?></td>
                    <?php 
			
			$data_array = Mage::getModel('deliverytime/deliverytime')->getCollection()->addFieldToSelect('*')->addFieldToFilter('status',1); 
			if(count($data_array)>0):
                        foreach($data_array as $key=>$value):
			?>
                    <td style="color:#999999"  <?php 
					echo (date("D", $ts)=='Mon' && $value->getmon()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Tue' && $value->gettue()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Wed' && $value->getwed()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Thu' && $value->getthu()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Fri' && $value->getfri()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Sat' && $value->getsat()==0)?'class="nohover"':'';
					echo (date("D", $ts)=='Sun' && $value->getsun()==0)?'class="nohover"':'';					
					?> ><label class="label">
                        <input id="exp" type="radio" class="btnradio" name="timeslot" value="<?php echo $value->getdeliverytime_start().' - '.$value->getdeliverytime_end().' '.date("d-m-Y D", $ts);?>" <?php 
							echo (date("D", $ts)=='Mon' && $value->getmon()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Tue' && $value->gettue()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Wed' && $value->getwed()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Thu' && $value->getthu()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Fri' && $value->getfri()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Sat' && $value->getsat()==0)?'disabled="disabled"':'';
							echo (date("D", $ts)=='Sun' && $value->getsun()==0)?'disabled="disabled"':'';					
					    ?>   />
                        <?php echo $value->getdeliverytime_start().' - '.$value->getdeliverytime_end();?></label></td>
                        
            <?php  endforeach; else:  ?>
                    <td> <h3 style="text-align:center;">No Time Slot Available </h3>  </td>      
            <?php endif; ?>
                  </tr>
                  <?php } ?>
                </table>
              </div>
            </li>
          </ul>
        </fieldset>
      </li>
</form>


<div class="button-set">
    <div id="deliverytime-buttons-container">
        <button type="button" class="button validation-passed" onclick="deliverytime.save();"><span><?php echo $this->__('Continue') ?></span></button>
        <span id="deliverytime-please-wait" style="display:none;" class="opc-please-wait">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
        </span>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[

var Deliverytime = Class.create();
Deliverytime.prototype = {
    initialize: function(form, saveUrl){
        this.form = form;
        if ($(this.form)) {
            $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
        }
        this.saveUrl = saveUrl;
        this.onSave = this.nextStep.bindAsEventListener(this);
        this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
    },

    save: function(){
        if (checkout.loadWaiting!=false) return;

        var validator = new Validation(this.form);
        if (validator.validate()) {

            checkout.setLoadWaiting('deliverytime');


            var request = new Ajax.Request(
                this.saveUrl,
                {
                    method: 'post',
                    onComplete: this.onComplete,
                    onSuccess: this.onSave,
                    onFailure: checkout.ajaxFailure.bind(checkout),
                    parameters: Form.serialize(this.form)
                }
            );
        }
    },

    resetLoadWaiting: function(transport){
        checkout.setLoadWaiting(false);
    },

    nextStep: function(transport){
        if (transport && transport.responseText){
            try{
                response = eval('(' + transport.responseText + ')');
            }
            catch (e) {
                response = {};
            }
        }

        if (response.error){
            if ((typeof response.message) == 'string') {
                alert(response.message);
            } else {
                if (window.billingRegionUpdater) {
                    billingRegionUpdater.update();
                }

                alert(response.message.join("\n"));
            }

            return false;
        }

        checkout.setStepResponse(response);
    }    
}

var deliverytime = new Deliverytime('co-deliverytime-form', '<?php echo $this->getUrl('checkout/onepage/saveDeliverytime') ?>');

$('shipping:same_as_entrant').observe('click',function(){
	if(this.checked){
		$('shipping:permanent').setValue($('shipping:local_address').value);
	}
	else{
		$('shipping:permanent').setValue('');	
	}
});

//]]>
</script>